local M = {}

M.plot_action = {
	name = "Adventure Plot Action",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Action", [2] = "Activity", [3] = "Attack", [4] = "Attempt",
		[5] = "Change", [6] = "Chase", [7] = "Collapse", [8] = "Command",
		[9] = "Counter", [10] = "Crash", [11] = "Culmination", [12] = "Damage",
		[13] = "Danger", [14] = "Delay", [15] = "Destroy", [16] = "Disarm",
		[17] = "Encounter", [18] = "Escape", [19] = "Event", [20] = "Failure",
		[21] = "Fight", [22] = "Flee", [23] = "Harm", [24] = "Impact",
		[25] = "Improvement", [26] = "Increase", [27] = "Intensify", [28] = "Invasion",
		[29] = "Launch", [30] = "Loss", [31] = "Movement", [32] = "Obstacle",
		[33] = "Progress", [34] = "Rescue", [35] = "Risk", [36] = "Step",
		[37] = "Strategy", [38] = "Strike", [39] = "Trouble", [40] = "Violence",
		[41] = "Warning", [42] = "Activity", [43] = "Attack", [44] = "Attempt",
		[45] = "Change", [46] = "Chase", [47] = "Collapse", [48] = "Command",
		[49] = "Counter", [50] = "Crash", [51] = "Culmination", [52] = "Damage",
		[53] = "Danger", [54] = "Delay", [55] = "Destroy", [56] = "Disarm",
		[57] = "Encounter", [58] = "Escape", [59] = "Event", [60] = "Failure",
		[61] = "Fight", [62] = "Flee", [63] = "Harm", [64] = "Impact",
		[65] = "Improvement", [66] = "Increase", [67] = "Intensify", [68] = "Invasion",
		[69] = "Launch", [70] = "Loss", [71] = "Movement", [72] = "Obstacle",
		[73] = "Progress", [74] = "Rescue", [75] = "Risk", [76] = "Step",
		[77] = "Strategy", [78] = "Strike", [79] = "Trouble", [80] = "Violence",
		[81] = "Warning", [82] = "Activity", [83] = "Attack", [84] = "Attempt",
		[85] = "Change", [86] = "Chase", [87] = "Collapse", [88] = "Command",
		[89] = "Counter", [90] = "Crash", [91] = "Culmination", [92] = "Damage",
		[93] = "Danger", [94] = "Delay", [95] = "Destroy", [96] = "Disarm",
		[97] = "Encounter", [98] = "Escape", [99] = "Event", [100] = "Failure",
	},
}

M.plot_tension = {
	name = "Adventure Plot Tension",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Abduction", [2] = "Accident", [3] = "Ambush", [4] = "Battle",
		[5] = "Catastrophe", [6] = "Competition", [7] = "Conflict", [8] = "Confrontation",
		[9] = "Collateral", [10] = "Chase", [11] = "Danger", [12] = "Depletion",
		[13] = "Desperate", [14] = "Destruction", [15] = "Disappearance", [16] = "Encounter",
		[17] = "Escape", [18] = "Event", [19] = "Exposure", [20] = "Failure",
		[21] = "Falling", [22] = "Horror", [23] = "Impending", [24] = "Intensify",
		[25] = "Intent", [26] = "Intimidation", [27] = "Obstacle", [28] = "Opponent",
		[29] = "Risk", [30] = "Severity", [31] = "Setback", [32] = "Suffering",
		[33] = "Threat", [34] = "Trouble", [35] = "Unclear", [36] = "Violence",
		[37] = "Vulnerability", [38] = "Abduction", [39] = "Accident", [40] = "Ambush",
		[41] = "Battle", [42] = "Catastrophe", [43] = "Competition", [44] = "Conflict",
		[45] = "Confrontation", [46] = "Collateral", [47] = "Chase", [48] = "Danger",
		[49] = "Depletion", [50] = "Desperate", [51] = "Destruction", [52] = "Disappearance",
		[53] = "Encounter", [54] = "Escape", [55] = "Event", [56] = "Exposure",
		[57] = "Failure", [58] = "Falling", [59] = "Horror", [60] = "Impending",
		[61] = "Intensify", [62] = "Intent", [63] = "Intimidation", [64] = "Obstacle",
		[65] = "Opponent", [66] = "Risk", [67] = "Severity", [68] = "Setback",
		[69] = "Suffering", [70] = "Threat", [71] = "Trouble", [72] = "Unclear",
		[73] = "Violence", [74] = "Vulnerability", [75] = "Abduction", [76] = "Accident",
		[77] = "Ambush", [78] = "Battle", [79] = "Catastrophe", [80] = "Competition",
		[81] = "Conflict", [82] = "Confrontation", [83] = "Collateral", [84] = "Chase",
		[85] = "Danger", [86] = "Depletion", [87] = "Desperate", [88] = "Destruction",
		[89] = "Disappearance", [90] = "Encounter", [91] = "Escape", [92] = "Event",
		[93] = "Exposure", [94] = "Failure", [95] = "Falling", [96] = "Horror",
		[97] = "Impending", [98] = "Intensify", [99] = "Intent", [100] = "Intimidation",
	},
}

M.plot_mystery = {
	name = "Adventure Plot Mystery",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "None", [2] = "Conclusion", [3] = "Crime", [4] = "Cryptic",
		[5] = "Discovery", [6] = "Disappearance", [7] = "Emergency", [8] = "Escape",
		[9] = "Hidden", [10] = "Impending", [11] = "Incapacitation", [12] = "Investigation",
		[13] = "Lie", [14] = "Location", [15] = "Motive", [16] = "Mystery",
		[17] = "Observation", [18] = "Possibility", [19] = "Secret", [20] = "Service",
		[21] = "Subversion", [22] = "Theory", [23] = "Threat", [24] = "Transaction",
		[25] = "Understanding", [26] = "None", [27] = "Conclusion", [28] = "Crime",
		[29] = "Cryptic", [30] = "Discovery", [31] = "Disappearance", [32] = "Emergency",
		[33] = "Escape", [34] = "Hidden", [35] = "Impending", [36] = "Incapacitation",
		[37] = "Investigation", [38] = "Lie", [39] = "Location", [40] = "Motive",
		[41] = "Mystery", [42] = "Observation", [43] = "Possibility", [44] = "Secret",
		[45] = "Service", [46] = "Subversion", [47] = "Theory", [48] = "Threat",
		[49] = "Transaction", [50] = "Understanding", [51] = "None", [52] = "Conclusion",
		[53] = "Crime", [54] = "Cryptic", [55] = "Discovery", [56] = "Disappearance",
		[57] = "Emergency", [58] = "Escape", [59] = "Hidden", [60] = "Impending",
		[61] = "Incapacitation", [62] = "Investigation", [63] = "Lie", [64] = "Location",
		[65] = "Motive", [66] = "Mystery", [67] = "Observation", [68] = "Possibility",
		[69] = "Secret", [70] = "Service", [71] = "Subversion", [72] = "Theory",
		[73] = "Threat", [74] = "Transaction", [75] = "Understanding", [76] = "None",
		[77] = "Conclusion", [78] = "Crime", [79] = "Cryptic", [80] = "Discovery",
		[81] = "Disappearance", [82] = "Emergency", [83] = "Escape", [84] = "Hidden",
		[85] = "Impending", [86] = "Incapacitation", [87] = "Investigation", [88] = "Lie",
		[89] = "Location", [90] = "Motive", [91] = "Mystery", [92] = "Observation",
		[93] = "Possibility", [94] = "Secret", [95] = "Service", [96] = "Subversion",
		[97] = "Theory", [98] = "Threat", [99] = "Transaction", [100] = "Understanding",
	},
}

M.plot_social = {
	name = "Adventure Plot Social",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Alternate", [2] = "Animosity", [3] = "Argument", [4] = "Behavior",
		[5] = "Celebration", [6] = "Coercion", [7] = "Communication", [8] = "Conflict",
		[9] = "Confrontation", [10] = "Coercion", [11] = "Connection", [12] = "Conversation",
		[13] = "Debate", [14] = "Decision", [15] = "Deception", [16] = "Delay",
		[17] = "Discussion", [18] = "Explanation", [19] = "Greeting", [20] = "Greeting",
		[21] = "Harassment", [22] = "Increase", [23] = "Instruction", [24] = "Meeting",
		[25] = "Miscommunication", [26] = "Negotiation", [27] = "Persuasion", [28] = "Proposal",
		[29] = "Rejection", [30] = "Request", [31] = "Response", [32] = "Revelation",
		[33] = "Social", [34] = "Solution", [35] = "Statement", [36] = "Support",
		[37] = "Tension", [38] = "Treatment", [39] = "Ultimatum", [40] = "Unclear",
		[41] = "Understanding", [42] = "Alternate", [43] = "Animosity", [44] = "Argument",
		[45] = "Behavior", [46] = "Celebration", [47] = "Coercion", [48] = "Communication",
		[49] = "Conflict", [50] = "Confrontation", [51] = "Coercion", [52] = "Connection",
		[53] = "Conversation", [54] = "Debate", [55] = "Decision", [56] = "Deception",
		[57] = "Delay", [58] = "Discussion", [59] = "Explanation", [60] = "Greeting",
		[61] = "Greeting", [62] = "Harassment", [63] = "Increase", [64] = "Instruction",
		[65] = "Meeting", [66] = "Miscommunication", [67] = "Negotiation", [68] = "Persuasion",
		[69] = "Proposal", [70] = "Rejection", [71] = "Request", [72] = "Response",
		[73] = "Revelation", [74] = "Social", [75] = "Solution", [76] = "Statement",
		[77] = "Support", [78] = "Tension", [79] = "Treatment", [80] = "Ultimatum",
		[81] = "Unclear", [82] = "Understanding", [83] = "Alternate", [84] = "Animosity",
		[85] = "Argument", [86] = "Behavior", [87] = "Celebration", [88] = "Coercion",
		[89] = "Communication", [90] = "Conflict", [91] = "Confrontation", [92] = "Coercion",
		[93] = "Connection", [94] = "Conversation", [95] = "Debate", [96] = "Decision",
		[97] = "Deception", [98] = "Delay", [99] = "Discussion", [100] = "Explanation",
	},
}

M.plot_personal = {
	name = "Adventure Plot Personal",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Agreement", [2] = "Alliance", [3] = "Betrayal", [4] = "Bribe",
		[5] = "Choice", [6] = "Clue", [7] = "Communication", [8] = "Connection",
		[9] = "Confrontation", [10] = "Dependent", [11] = "Desperate", [12] = "Discovery",
		[13] = "Disagreement", [14] = "Disarmed", [15] = "Disempowered", [16] = "Emotional",
		[17] = "Empowered", [18] = "Failure", [19] = "Feasibility", [20] = "Guidance",
		[21] = "Help", [22] = "Hindrance", [23] = "Hope", [24] = "Importance",
		[25] = "Inexperience", [26] = "Instruction", [27] = "Necessity", [28] = "Obstacle",
		[29] = "Offer", [30] = "Opinion", [31] = "Opportunity", [32] = "Possibility",
		[33] = "Pressure", [34] = "Protection", [35] = "Provision", [36] = "Question",
		[37] = "Reasoning", [38] = "Request", [39] = "Requirement", [40] = "Resource",
		[41] = "Review", [42] = "Sacrifice", [43] = "Significance", [44] = "Struggle",
		[45] = "Support", [46] = "Task", [47] = "Thought", [48] = "Trouble",
		[49] = "Understanding", [50] = "Value", [51] = "Agreement", [52] = "Alliance",
		[53] = "Betrayal", [54] = "Bribe", [55] = "Choice", [56] = "Clue",
		[57] = "Communication", [58] = "Connection", [59] = "Confrontation", [60] = "Dependent",
		[61] = "Desperate", [62] = "Discovery", [63] = "Disagreement", [64] = "Disarmed",
		[65] = "Disempowered", [66] = "Emotional", [67] = "Empowered", [68] = "Failure",
		[69] = "Feasibility", [70] = "Guidance", [71] = "Help", [72] = "Hindrance",
		[73] = "Hope", [74] = "Importance", [75] = "Inexperience", [76] = "Instruction",
		[77] = "Necessity", [78] = "Obstacle", [79] = "Offer", [80] = "Opinion",
		[81] = "Opportunity", [82] = "Possibility", [83] = "Pressure", [84] = "Protection",
		[85] = "Provision", [86] = "Question", [87] = "Reasoning", [88] = "Request",
		[89] = "Requirement", [90] = "Resource", [91] = "Review", [92] = "Sacrifice",
		[93] = "Significance", [94] = "Struggle", [95] = "Support", [96] = "Task",
		[97] = "Thought", [98] = "Trouble", [99] = "Understanding", [100] = "Value",
	},
}

M.themes = {
	name = "Adventure Themes",
	type = "simple",
	dice = "1d10",
	entries = {
		[1] = "Action",
		[2] = "Action",
		[3] = "Tension",
		[4] = "Tension",
		[5] = "Mystery",
		[6] = "Mystery",
		[7] = "Social",
		[8] = "Social",
		[9] = "Personal",
		[10] = "Personal",
	},
}

return M
