local M = {}

M.identity = {
	name = "Character Identity Keywords",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Academic", [2] = "Accepted", [3] = "Acting", [4] = "Aggressive",
		[5] = "Alien", [6] = "Ancestral", [7] = "Angry", [8] = "Animated",
		[9] = "Artisan", [10] = "Artistic", [11] = "Athletic", [12] = "Attractive",
		[13] = "Authority", [14] = "Brutal", [15] = "Building", [16] = "Calm",
		[17] = "Career", [18] = "Casual", [19] = "Celebrity", [20] = "Cheat",
		[21] = "Clergy", [22] = "Colonial", [23] = "Combat", [24] = "Common",
		[25] = "Companion", [26] = "Compassionate", [27] = "Competitive", [28] = "Complex",
		[29] = "Concept", [30] = "Confidential", [31] = "Connected", [32] = "Conservative",
		[33] = "Construction", [34] = "Controller", [35] = "Common", [36] = "Connected",
		[37] = "Conscious", [38] = "Consistent", [39] = "Constructor", [40] = "Consulting",
		[41] = "Cook", [42] = "Cool", [43] = "Corrupt", [44] = "Counterfeit",
		[45] = "Creative", [46] = "Criminal", [47] = "Danger", [48] = "Deadly",
		[49] = "Decadent", [50] = "Dedicated", [51] = "Deceptive", [52] = "Deliberate",
		[53] = "Desperate", [54] = "Destructive", [55] = "Different", [56] = "Dirty",
		[57] = "Discovered", [58] = "Elite", [59] = "Entertainer", [60] = "Established",
		[61] = "Experienced", [62] = "Expert", [63] = "Explorer", [64] = "Extraordinary",
		[65] = "Family", [66] = "Fast", [67] = "Finesse", [68] = "Military",
		[69] = "Miserable", [70] = "Mythic", [71] = "Natural", [72] = "Noble",
		[73] = "Normal", [74] = "Notable", [75] = "Observant", [76] = "Old",
		[77] = "Ordered", [78] = "Outdoors", [79] = "Outrageous", [80] = "Outside",
		[81] = "Perfectionist", [82] = "Professional", [83] = "Protective", [84] = "Questing",
		[85] = "Rare", [86] = "Reformed", [87] = "Religious", [88] = "Renowned",
		[89] = "Research", [90] = "Reserved", [91] = "Responsible", [92] = "Rich",
		[93] = "Secretive", [94] = "Skilled", [95] = "Social", [96] = "Soldier",
		[97] = "Special", [98] = "Strange", [99] = "Strong", [100] = "Violent",
	},
}

M.talent = {
	name = "Character Talent Keywords",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Academic", [2] = "Acting", [3] = "Aggressive", [4] = "Alien",
		[5] = "Animals", [6] = "Animated", [7] = "Artisan", [8] = "Artistic",
		[9] = "Athletic", [10] = "Attractive", [11] = "Chaotic", [12] = "Combat",
		[13] = "Command", [14] = "Compassion", [15] = "Complex", [16] = "Connection",
		[17] = "Conservation", [18] = "Contact", [19] = "Control", [20] = "Covert",
		[21] = "Creative", [22] = "Criminal", [23] = "Critical", [24] = "Deceptive",
		[25] = "Defense", [26] = "Desperate", [27] = "Detect", [28] = "Detect",
		[29] = "Discipline", [30] = "Education", [31] = "Elements", [32] = "Eloquent",
		[33] = "Emotional", [34] = "Endurance", [35] = "Finesse", [36] = "Flee",
		[37] = "Focused", [38] = "Fortune", [39] = "Found", [40] = "Gaming",
		[41] = "Goods", [42] = "Graceful", [43] = "Handling", [44] = "Hardy",
		[45] = "Healing", [46] = "Heritage", [47] = "Heroic", [48] = "Hidden",
		[49] = "High", [50] = "History", [51] = "Honesty", [52] = "Horror",
		[53] = "Hostile", [54] = "Insight", [55] = "Inspire", [56] = "Instruct",
		[57] = "Intimidate", [58] = "Investigation", [59] = "Knowledge", [60] = "Language",
		[61] = "Leadership", [62] = "Learned", [63] = "Locate", [64] = "Lucky",
		[65] = "Magic", [66] = "Mechanical", [67] = "Mind", [68] = "Military",
		[69] = "Mythic", [70] = "Natural", [71] = "Observant", [72] = "Official",
		[73] = "Outside", [74] = "Outsider", [75] = "Perceptive", [76] = "Performance",
		[77] = "Permanent", [78] = "Persistent", [79] = "Physical", [80] = "Pirate",
		[81] = "Plan", [82] = "Poor", [83] = "Portal", [84] = "Possession",
		[85] = "Power", [86] = "Pretend", [87] = "Professional", [88] = "Prophecy",
		[89] = "Protection", [90] = "Questing", [91] = "Rare", [92] = "Reformed",
		[93] = "Religious", [94] = "Reputation", [95] = "Research", [96] = "Resource",
		[97] = "Science", [98] = "Sensitive", [99] = "Service", [100] = "Weapon",
	},
}

M.body = {
	name = "Character Body Keywords",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Academic", [2] = "Acting", [3] = "Aggressive", [4] = "Alien",
		[5] = "Animals", [6] = "Animated", [7] = "Appearance", [8] = "Artisan",
		[9] = "Artistic", [10] = "Athletic", [11] = "Attack", [12] = "Attractive",
		[13] = "Blending", [14] = "Body", [15] = "Carrying", [16] = "Chaos",
		[17] = "Clothing", [18] = "Combat", [19] = "Companion", [20] = "Connection",
		[21] = "Control", [22] = "Cool", [23] = "Coordination", [24] = "Dangerous",
		[25] = "Defense", [26] = "Desperate", [27] = "Detect", [28] = "Dirty",
		[29] = "Discipline", [30] = "Disguise", [31] = "Emotion", [32] = "Endurance",
		[33] = "Entertainer", [34] = "Equipment", [35] = "Finesse", [36] = "Flee",
		[37] = "Focused", [38] = "Fortune", [39] = "Found", [40] = "Fragile",
		[41] = "Games", [42] = "Goods", [43] = "Graceful", [44] = "Handle",
		[45] = "Hardy", [46] = "Harm", [47] = "Heritage", [48] = "Heroic",
		[49] = "Hidden", [50] = "High", [51] = "History", [52] = "Honesty",
		[53] = "Horror", [54] = "Hostile", [55] = "Identify", [56] = "Important",
		[57] = "Inanimate", [58] = "Information", [59] = "Insight", [60] = "Instruct",
		[61] = "Intelligence", [62] = "Intimidate", [63] = "Investigation", [64] = "Knowledge",
		[65] = "Language", [66] = "Locate", [67] = "Object", [68] = "Obstacle",
		[69] = "Official", [70] = "Old", [71] = "Opportunity", [72] = "Order",
		[73] = "Organized", [74] = "Outside", [75] = "Overwhelming", [76] = "Ownership",
		[77] = "Patient", [78] = "Perception", [79] = "Performance", [80] = "Permanent",
		[81] = "Permitted", [82] = "Personal", [83] = "Physical", [84] = "Poor",
		[85] = "Portal", [86] = "Possession", [87] = "Power", [88] = "Pretend",
		[89] = "Primitive", [90] = "Protection", [91] = "Purpose", [92] = "Rare",
		[93] = "Reformed", [94] = "Religious", [95] = "Reputation", [96] = "Resource",
		[97] = "Science", [98] = "Service", [99] = "Weapon", [100] = "Wounded",
	},
}

M.mind = {
	name = "Character Mind Keywords",
	type = "simple",
	dice = "1d100",
	entries = {
		[1] = "Academic", [2] = "Acting", [3] = "Aggressive", [4] = "Alien",
		[5] = "Analyze", [6] = "Animated", [7] = "Answer", [8] = "Anticipation",
		[9] = "Application", [10] = "Approach", [11] = "Artisan", [12] = "Attractive",
		[13] = "Authority", [14] = "Behavioral", [15] = "Calculation", [16] = "Cause",
		[17] = "Combat", [18] = "Command", [19] = "Compassion", [20] = "Complex",
		[21] = "Concept", [22] = "Connection", [23] = "Consultation", [24] = "Conversation",
		[25] = "Coordinated", [26] = "Creative", [27] = "Critical", [28] = "Curious",
		[29] = "Danger", [30] = "Decision", [31] = "Deliberate", [32] = "Desperate",
		[33] = "Detect", [34] = "Education", [35] = "Insight", [36] = "Instruct",
		[37] = "Intelligence", [38] = "Intimidate", [39] = "Investigation", [40] = "Knowledge",
		[41] = "Language", [42] = "Leadership", [43] = "Logic", [44] = "Lore",
		[45] = "Low", [46] = "Magic", [47] = "Mechanical", [48] = "Memory",
		[49] = "Meticulous", [50] = "Mind", [51] = "Mystery", [52] = "Natural",
		[53] = "Navigation", [54] = "New", [55] = "Objective", [56] = "Observation",
		[57] = "Official", [58] = "Old", [59] = "One", [60] = "Open",
		[61] = "Opportunity", [62] = "Optimistic", [63] = "Organized", [64] = "Other",
		[65] = "Outside", [66] = "Overwhelming", [67] = "Perception", [68] = "Official",
		[69] = "Old", [70] = "Opportunity", [71] = "Ordered", [72] = "Organized",
		[73] = "Outside", [74] = "Overwhelming", [75] = "Perception", [76] = "Performance",
		[77] = "Permanent", [78] = "Permitted", [79] = "Personal", [80] = "Planning",
		[81] = "Poor", [82] = "Portal", [83] = "Possession", [84] = "Power",
		[85] = "Pretend", [86] = "Pretend", [87] = "Primitive", [88] = "Professional",
		[89] = "Protection", [90] = "Purpose", [91] = "Quick", [92] = "Rare",
		[93] = "Reformed", [94] = "Religious", [95] = "Reputation", [96] = "Research",
		[97] = "Resource", [98] = "Science", [99] = "Serious", [100] = "Weapon",
	},
}

return M
