local M = {}

M.action = {
	name = "Meaning Action",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Attain" },
		{ min = 3, max = 4, result = "Benefit" },
		{ min = 5, max = 6, result = "Betray" },
		{ min = 7, max = 8, result = "Break" },
		{ min = 9, max = 10, result = "Burden" },
		{ min = 11, max = 12, result = "Change" },
		{ min = 13, max = 14, result = "Character" },
		{ min = 15, max = 16, result = "Communicate" },
		{ min = 17, max = 18, result = "Competition" },
		{ min = 19, max = 20, result = "Conclude" },
		{ min = 21, max = 22, result = "Conflict" },
		{ min = 23, max = 24, result = "Control" },
		{ min = 25, max = 26, result = "Create" },
		{ min = 27, max = 28, result = "Danger" },
		{ min = 29, max = 30, result = "Deceit" },
		{ min = 31, max = 32, result = "Decrease" },
		{ min = 33, max = 34, result = "Delay" },
		{ min = 35, max = 36, result = "Distant" },
		{ min = 37, max = 38, result = "Emotions" },
		{ min = 39, max = 40, result = "Enemies" },
		{ min = 41, max = 42, result = "Environment" },
		{ min = 43, max = 44, result = "Expectations" },
		{ min = 45, max = 46, result = "Failure" },
		{ min = 47, max = 48, result = "Fears" },
		{ min = 49, max = 50, result = "Fight" },
		{ min = 51, max = 52, result = "Gain" },
		{ min = 53, max = 54, result = "Goals" },
		{ min = 55, max = 56, result = "Good" },
		{ min = 57, max = 58, result = "Harm" },
		{ min = 59, max = 60, result = "Help" },
		{ min = 61, max = 62, result = "Increase" },
		{ min = 63, max = 64, result = "Information" },
		{ min = 65, max = 66, result = "Leave" },
		{ min = 67, max = 68, result = "Move" },
		{ min = 69, max = 70, result = "Mundane" },
		{ min = 71, max = 72, result = "Nature" },
		{ min = 73, max = 74, result = "Negative" },
		{ min = 75, max = 76, result = "NPC" },
		{ min = 77, max = 78, result = "Object" },
		{ min = 79, max = 80, result = "Obstacle" },
		{ min = 81, max = 82, result = "Official" },
		{ min = 83, max = 84, result = "PC" },
		{ min = 85, max = 86, result = "Positive" },
		{ min = 87, max = 88, result = "Progress" },
		{ min = 89, max = 90, result = "Setback" },
		{ min = 91, max = 92, result = "Start" },
		{ min = 93, max = 94, result = "Stop" },
		{ min = 95, max = 96, result = "Strange" },
		{ min = 97, max = 98, result = "Surprise" },
		{ min = 99, max = 100, result = "Uncertain" },
	},
}

M.description = {
	name = "Meaning Description",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Artificial" },
		{ min = 3, max = 4, result = "Beautiful" },
		{ min = 5, max = 6, result = "Bleak" },
		{ min = 7, max = 8, result = "Bright" },
		{ min = 9, max = 10, result = "Clean" },
		{ min = 11, max = 12, result = "Cold" },
		{ min = 13, max = 14, result = "Colorful" },
		{ min = 15, max = 16, result = "Damaged" },
		{ min = 17, max = 18, result = "Dangerous" },
		{ min = 19, max = 20, result = "Dark" },
		{ min = 21, max = 22, result = "Dirty" },
		{ min = 23, max = 24, result = "Disagreeable" },
		{ min = 25, max = 26, result = "Empty" },
		{ min = 27, max = 28, result = "Extravagant" },
		{ min = 29, max = 30, result = "Feeble" },
		{ min = 31, max = 32, result = "Fragrant" },
		{ min = 33, max = 34, result = "Frightening" },
		{ min = 35, max = 36, result = "Full" },
		{ min = 37, max = 38, result = "Healthy" },
		{ min = 39, max = 40, result = "Heavy" },
		{ min = 41, max = 42, result = "Helpful" },
		{ min = 43, max = 44, result = "Important" },
		{ min = 45, max = 46, result = "Incomplete" },
		{ min = 47, max = 48, result = "Lacking" },
		{ min = 49, max = 50, result = "Large" },
		{ min = 51, max = 52, result = "Light" },
		{ min = 53, max = 54, result = "Loud" },
		{ min = 55, max = 56, result = "Mechanical" },
		{ min = 57, max = 58, result = "Modern" },
		{ min = 59, max = 60, result = "Mundane" },
		{ min = 61, max = 62, result = "Mysterious" },
		{ min = 63, max = 64, result = "Natural" },
		{ min = 65, max = 66, result = "New" },
		{ min = 67, max = 68, result = "Official" },
		{ min = 69, max = 70, result = "Old" },
		{ min = 71, max = 72, result = "Peaceful" },
		{ min = 73, max = 74, result = "Perfect" },
		{ min = 75, max = 76, result = "Powerful" },
		{ min = 77, max = 78, result = "Quiet" },
		{ min = 79, max = 80, result = "Reassuring" },
		{ min = 81, max = 82, result = "Rotten" },
		{ min = 83, max = 84, result = "Rough" },
		{ min = 85, max = 86, result = "Rustic" },
		{ min = 87, max = 88, result = "Simple" },
		{ min = 89, max = 90, result = "Small" },
		{ min = 91, max = 92, result = "Strange" },
		{ min = 93, max = 94, result = "Stylish" },
		{ min = 95, max = 96, result = "Valuable" },
		{ min = 97, max = 98, result = "Warm" },
		{ min = 99, max = 100, result = "Weird" },
	},
}

return M
